# Generated by Django 4.0.5 on 2022-06-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_testing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
