# Generated by Django 3.2.13 on 2022-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
