# Generated by Django 3.2.13 on 2022-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_author_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='info',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
